server:
  port: 8080


spring:
  application:
    name: staro
  virtual:
    thread:
      thread-name-prefix: spring-vt-
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    custom-css-url: https://cdn.jsdelivr.net/npm/swagger-ui-themes@3.0.1/themes/3.x/theme-material.css
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
    filter: true
    persistAuthorization: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packages-to-scan: com.your.package
  cache:
    disabled: true